# Dockerizing Kannel: bearerbox role
# Based on ubuntu:latest, installs and runs Kannel's bearerbox

# Format: FROM    repository[:version]
FROM jdub/kannel

# Format: MAINTAINER Name <email@addr.ess>
MAINTAINER Jdub

CMD bearerbox /etc/kannel/kannel.conf