# Dockerizing Kannel: smsbox role
# Based on ubuntu:latest, installs and runs Kannel's smsbox

# Format: FROM    repository[:version]
FROM jdub/kannel

# Format: MAINTAINER Name <email@addr.ess>
MAINTAINER Jdub

CMD smsbox /etc/kannel/kannel.conf